version: '3.8'

services:
  db:
    image: mysql:8.0
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
      MYSQL_DATABASE: Budgets
    ports:
      - "3306:3306"
    volumes:
      - db-data:/var/lib/mysql

  app:
    build:
      context: .
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://dbrenovariontp.cxos66asoca1.eu-north-1.rds.amazonaws.com:3306/tpreformas
      SPRING_DATASOURCE_USERNAME: tp32grs531
      SPRING_DATASOURCE_PASSWORD: s34*45%)gfd&SDF_5!4dWWD1
      SPRING_DATASOURCE_DRIVER_CLASS_NAME: com.mysql.cj.jdbc.Driver
    depends_on:
      - db

volumes:
  db-data:
